import { Alert, Button, Card, Col, Form, Input, Row, Steps, Typography, Upload } from 'antd'
import { FileJson, UploadCloud } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import type { UploadFile } from 'antd'
import { api } from '../api/client'

export function ImportPage(){const [schema,setSchema]=useState<UploadFile[]>([]);const [view,setView]=useState<UploadFile[]>([]);const [data,setData]=useState<UploadFile[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const navigate=useNavigate();const submit=async(values:Record<string,string>)=>{if(!schema[0]?.originFileObj||!data[0]?.originFileObj){setError('请选择 Schema 与 JSON/JSONL 数据文件');return}setLoading(true);setError('');try{const form=new FormData();Object.entries(values).forEach(([key,value])=>form.append(key,value));form.append('schema_file',schema[0].originFileObj);form.append('data_file',data[0].originFileObj);if(view[0]?.originFileObj)form.append('view_file',view[0].originFileObj);const result=await api.importProject(form);navigate(`/project/${result.project_id}/table?batch=${result.batch_id}`)}catch(e){setError((e as Error).message)}finally{setLoading(false)}};const uploadProps=(files:UploadFile[],setter:(files:UploadFile[])=>void,accept:string)=>({fileList:files,accept,beforeUpload:()=>false,onChange:({fileList}:{fileList:UploadFile[]})=>setter(fileList.slice(-1))});return <main className="page narrow-page"><Typography.Title>导入 Schema 与数据</Typography.Title><Typography.Paragraph type="secondary">一次导入创建项目、数据批次和不可变的原始数据副本。</Typography.Paragraph><Steps current={0} items={[{title:'选择配置'},{title:'解析与校验'},{title:'进入工作区'}]}/>{error&&<Alert style={{marginTop:20}} type="error" showIcon message={error}/>}<Form layout="vertical" onFinish={submit} initialValues={{batch_name:'首批数据',data_version:'v1'}}><Card className="import-card" title="项目信息"><Row gutter={16}><Col span={12}><Form.Item name="project_name" label="项目名称" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={12}><Form.Item name="batch_name" label="批次名称"><Input/></Form.Item></Col><Col span={12}><Form.Item name="data_version" label="数据版本"><Input/></Form.Item></Col><Col span={24}><Form.Item name="description" label="项目说明"><Input.TextArea/></Form.Item></Col></Row></Card><Row gutter={16}><Col span={8}><Upload.Dragger {...uploadProps(schema,setSchema,'.json')}><FileJson/><p>Schema JSON</p><small>字段、类型、约束与业务规则</small></Upload.Dragger></Col><Col span={8}><Upload.Dragger {...uploadProps(view,setView,'.json')}><FileJson/><p>View JSON（可选）</p><small>表格列和表单分组</small></Upload.Dragger></Col><Col span={8}><Upload.Dragger {...uploadProps(data,setData,'.json,.jsonl')}><UploadCloud/><p>数据 JSON / JSONL</p><small>Codex 结构化输出</small></Upload.Dragger></Col></Row><Button type="primary" htmlType="submit" size="large" loading={loading} block style={{marginTop:24}}>解析、校验并导入</Button></Form></main>}

