import { Alert, Button, Card, Col, List, Row, Space, Statistic, Tabs, Tag, Typography } from 'antd'
import { ArrowRight, Braces, Database, FileJson } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { api } from '../api/client'
import type { Project, ProjectSchema, ViewConfig } from '../types'

export function ProjectOverviewPage(){const {projectId}=useParams();const [project,setProject]=useState<Project|null>(null);const [schema,setSchema]=useState<ProjectSchema|null>(null);const [view,setView]=useState<ViewConfig|null>(null);const [error,setError]=useState('');const navigate=useNavigate();useEffect(()=>{let active=true;Promise.all([api.project(Number(projectId)),api.schema(Number(projectId)),api.view(Number(projectId))]).then(([nextProject,nextSchema,nextView])=>{if(!active)return;setProject(nextProject);setSchema(nextSchema);setView(nextView)}).catch((e)=>setError(e.message));return()=>{active=false}},[projectId]);if(error)return <main className="page"><Alert type="error" message={error}/></main>;if(!project||!schema||!view)return <main className="page">正在加载项目概览…</main>;return <main className="page"><header className="page-title"><div><span className="eyebrow">Project overview</span><Space><Typography.Title>{project.name}</Typography.Title><Tag>{project.schema_id} · v{project.schema_version}</Tag></Space><Typography.Paragraph type="secondary">{project.description}</Typography.Paragraph></div><Button type="primary" size="large" onClick={()=>project.latest_batch_id&&navigate(`/project/${project.id}/table?batch=${project.latest_batch_id}`)}>打开最新工作区 <ArrowRight size={16}/></Button></header><Row gutter={16}><Col span={6}><Card><Statistic title="记录" value={project.record_count} prefix={<Database size={16}/>}/></Card></Col><Col span={6}><Card><Statistic title="已通过" value={project.approved_count}/></Card></Col><Col span={6}><Card><Statistic title="需要复核" value={project.needs_review_count}/></Card></Col><Col span={6}><Card><Statistic title="校验错误" value={project.invalid_count}/></Card></Col></Row><Row gutter={20} style={{marginTop:20}}><Col span={9}><Card title="数据批次" extra={<FileJson size={17}/>}><List dataSource={project.batches??[]} renderItem={(batch)=><List.Item actions={[<Button type="link" onClick={()=>navigate(`/project/${project.id}/table?batch=${batch.id}`)}>打开</Button>]}><List.Item.Meta title={batch.name} description={`${batch.source_filename} · ${batch.record_count} 条 · ${batch.data_version}`}/></List.Item>}/></Card></Col><Col span={15}><Card title="项目配置" extra={<Braces size={17}/>}><Tabs items={[{key:'schema',label:'Schema',children:<pre className="json-code">{JSON.stringify(schema,null,2)}</pre>},{key:'view',label:'View 配置',children:<pre className="json-code">{JSON.stringify(view,null,2)}</pre>}]} /></Card></Col></Row></main>}

