import { Alert, App as AntdApp, Button, Card, Col, Collapse, Descriptions, Divider, Empty, Input, Row, Select, Space, Spin, Tabs, Tag, Typography } from 'antd'
import { CheckCircle2, Copy, Save, ShieldCheck, Trash2 } from 'lucide-react'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { FormProvider, useForm, useWatch } from 'react-hook-form'
import { useNavigate, useParams } from 'react-router-dom'
import { api } from '../api/client'
import { AIAnnotationView } from '../components/AIAnnotationView/AIAnnotationView'
import { DynamicForm } from '../components/DynamicForm/DynamicForm'
import { CommentEvidenceList } from '../components/CommentEvidenceList/CommentEvidenceList'
import { EvidenceTimeline } from '../components/EvidenceTimeline/EvidenceTimeline'
import type { Assignment, CommentEvidence, EvidenceSpan, FrameEvidence, SampleDetail } from '../types'

const decisions=[
  {value:'accept',label:'接受 AI'},{value:'minor_edit',label:'小改'},{value:'major_edit',label:'大改'},{value:'delete',label:'删除'},
  {value:'supplement',label:'补充'},{value:'unverifiable',label:'不可验证'},{value:'hallucination',label:'模型幻觉'},{value:'key_detail_missing',label:'关键细节遗漏'},
]

export function SampleWorkbenchPage(){
  const {message}=AntdApp.useApp()
  const {assignmentId}=useParams();const navigate=useNavigate();const video=useRef<HTMLVideoElement|null>(null);const hydrated=useRef(false);const activity=useRef({last:0,pending:0})
  const methods=useForm<Record<string,unknown>>({defaultValues:{}});const annotation=useWatch({control:methods.control}) as Record<string,unknown>
  const [assignment,setAssignment]=useState<Assignment|null>(null);const [sample,setSample]=useState<SampleDetail|null>(null);const [frames,setFrames]=useState<FrameEvidence[]>([]);const [comments,setComments]=useState<CommentEvidence[]>([])
  const [spans,setSpans]=useState<EvidenceSpan[]>([]);const [fieldDecisions,setFieldDecisions]=useState<Record<string,string>>({});const [errors,setErrors]=useState<Record<string,string>>({});const [saving,setSaving]=useState(false);const [saved,setSaved]=useState('');const [loop,setLoop]=useState(false);const [duration,setDuration]=useState(0);const [currentTime,setCurrentTime]=useState(0);const [reason,setReason]=useState('')
  useEffect(()=>{hydrated.current=false;Promise.all([api.assignment(Number(assignmentId))]).then(async([task])=>{setAssignment(task);methods.reset(task.human_annotation.current_data);setSpans(task.human_annotation.evidence_spans||[]);setFieldDecisions(task.human_annotation.field_decisions||{});const detail=await api.sample(task.sample_record_id,task.id);setSample(detail);setDuration(Number(detail.data.duration_seconds||detail.data.video_duration||0));const evidence=task.evidence_config;setFrames(evidence.frames?await api.frames(task.sample_record_id,task.id):[]);setComments(evidence.comments?await api.comments(task.sample_record_id,task.id):[]);activity.current={last:Date.now(),pending:0};setTimeout(()=>{hydrated.current=true},0)}).catch((e)=>message.error((e as Error).message))},[assignmentId,methods,message])
  const markActivity=useCallback(()=>{const now=Date.now();if(activity.current.last&&now-activity.current.last<=30000)activity.current.pending+=(now-activity.current.last)/1000;activity.current.last=now},[])
  const payload=()=>{markActivity();return {annotation:methods.getValues(),field_decisions:fieldDecisions,evidence_spans:spans,reason,active_seconds:activity.current.pending}}
  const save=async(silent=false)=>{if(!assignment||assignment.human_annotation.locked)return;setSaving(true);try{const result=await api.saveDraft(assignment.id,payload());setErrors(Object.fromEntries(result.validation_errors.map(item=>[item.path,item.message])));setSaved(new Date().toLocaleTimeString());activity.current.pending=0;if(!silent)message.success('草稿已保存')}catch(e){if(!silent)message.error((e as Error).message)}finally{setSaving(false)}}
  const serialized=JSON.stringify({annotation,fieldDecisions,spans,reason})
  useEffect(()=>{if(!hydrated.current||!assignment||assignment.human_annotation.locked)return;const timer=setTimeout(()=>void save(true),1400);return()=>clearTimeout(timer)},[serialized]) // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(!video.current||['INPUT','TEXTAREA'].includes((event.target as HTMLElement).tagName))return;if(event.code==='Space'){event.preventDefault();if(video.current.paused)void video.current.play();else video.current.pause()}if(event.key==='ArrowLeft')video.current.currentTime=Math.max(0,video.current.currentTime-1);if(event.key==='ArrowRight')video.current.currentTime=Math.min(duration,video.current.currentTime+1)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[duration])
  useEffect(()=>{const active=()=>markActivity();window.addEventListener('pointerdown',active);window.addEventListener('input',active);window.addEventListener('keydown',active);return()=>{window.removeEventListener('pointerdown',active);window.removeEventListener('input',active);window.removeEventListener('keydown',active)}},[markActivity])
  const submit=async()=>{if(!assignment)return;setSaving(true);try{const result=await api.submitAssignment(assignment.id,payload());setAssignment({...assignment,status:result.status,human_annotation:{...assignment.human_annotation,locked:true,submitted_data:methods.getValues()}});message.success('已提交并锁定')}catch(e){const text=(e as Error).message;message.error(text)}finally{setSaving(false)}}
  const acceptAI=(key:string)=>{const value=assignment?.ai_raw_annotation?.raw_output[key];if(value!==undefined){methods.setValue(key,value,{shouldDirty:true});setFieldDecisions({...fieldDecisions,[key]:'accept'})}}
  const locked=assignment?.human_annotation.locked??false
  const primary=spans.find(span=>span.primary&&!span.unlocatable)
  const frameCards=useMemo(()=>frames.map(frame=><button className={`frame-card ${primary&&frame.time_seconds>=(primary.start??0)&&frame.time_seconds<=(primary.end??0)?'in-span':''}`} key={frame.frame_id} onClick={()=>{if(video.current)video.current.currentTime=frame.time_seconds}}><img src={`/api/samples/${assignment?.sample_record_id}/frames/${encodeURIComponent(frame.frame_id)}/media?assignment_id=${assignment?.id}`} alt={`${frame.frame_set} ${frame.time_seconds}s`}/><span>{frame.time_seconds.toFixed(1)}s · {frame.frame_set}</span></button>),[frames,primary,assignment])
  if(!assignment||!sample)return <main className="page"><Spin/> 正在加载多模态工作台…</main>
  return <main className="workbench-page">
    <header className="workbench-header"><div><Button type="link" onClick={()=>navigate(`/research/project/${assignment.project_id}?dataset=${assignment.dataset_version_id}`)}>← 返回队列</Button><Typography.Title level={3}>{assignment.sample_id} · 样本工作台</Typography.Title></div><Space><Tag>{assignment.stage}</Tag><Tag color={assignment.blind?'purple':'blue'}>{assignment.blind?'盲标':'AI 辅助'}</Tag><Tag color={locked?'green':'orange'}>{locked?'已提交锁定':saved?`自动保存 ${saved}`:'草稿'}</Tag></Space></header>
    {locked&&<Alert type="success" showIcon icon={<ShieldCheck/>} message="个人结果已提交锁定；修改必须由研究管理员重开，AI 原始结果和清洗数据保持不变。"/>}
    <Row gutter={14} className="workbench-grid">
      <Col span={5}><Card className="comment-panel" title={<span>评论证据 <Tag variant="filled">{comments.length}</Tag></span>} size="small"><CommentEvidenceList comments={comments}/></Card></Col>
      <Col span={11}><Card title="视频与时间证据" size="small"><video ref={video} className="research-video" controls src={`/api/samples/${sample.sample_record_id}/media/video?assignment_id=${assignment.id}`} onLoadedMetadata={(event)=>setDuration(event.currentTarget.duration||duration)} onTimeUpdate={(event)=>{markActivity();setCurrentTime(event.currentTarget.currentTime);if(loop&&primary?.end&&event.currentTarget.currentTime>=primary.end){event.currentTarget.currentTime=primary.start??0;void event.currentTarget.play()}}}>浏览器无法播放该视频。</video><Typography.Text type="secondary">快捷键：空格播放/暂停，←/→ 快退或快进 1 秒。连续 30 秒无交互后停止累计活跃时长。</Typography.Text><Divider/><EvidenceTimeline spans={spans} duration={duration||1} currentTime={currentTime} onSeek={(seconds)=>{if(video.current){video.current.currentTime=seconds;void video.current.play()}}} onChange={setSpans} loop={loop} onLoop={setLoop}/><Divider/><Typography.Title level={5}>抽帧联动</Typography.Title><div className="frame-strip">{frameCards.length?frameCards:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="当前组没有抽帧权限或数据"/>}</div></Card></Col>
      <Col span={8}><Card className="ai-result-card" title="AI 原始结果（只读）" size="small">{assignment.ai_raw_annotation?<><Tag color="green">不可覆盖 · Run {assignment.ai_raw_annotation.model_run_id}</Tag><AIAnnotationView data={assignment.ai_raw_annotation.raw_output} schema={assignment.annotation_schema} view={assignment.view_config}/></>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={assignment.blind?'盲标组不提供 AI 建议':'尚未导入 AI 预编码'}/>}</Card><FormProvider {...methods}><div className={locked?'locked-form':''}><DynamicForm schema={assignment.annotation_schema} view={assignment.view_config} errors={errors}/></div></FormProvider><Card title="逐字段决定" size="small">{assignment.annotation_schema.fields.map(field=><div className="decision-row" key={field.key}><span>{field.label}</span><Space><Select value={fieldDecisions[field.key]} options={decisions} allowClear placeholder="选择处理方式" style={{width:135}} disabled={locked} onChange={(value)=>setFieldDecisions({...fieldDecisions,[field.key]:value})}/>{assignment.ai_raw_annotation&&<Button title="复制 AI 值" icon={<Copy size={14}/>} disabled={locked} onClick={()=>acceptAI(field.key)}/>}<Button title="清除人工值" icon={<Trash2 size={14}/>} disabled={locked} onClick={()=>{methods.setValue(field.key,undefined,{shouldDirty:true});setFieldDecisions({...fieldDecisions,[field.key]:'delete'})}}/></Space></div>)}<Input.TextArea value={reason} disabled={locked} onChange={e=>setReason(e.target.value)} placeholder="本次修改原因或备注" rows={2}/><Space style={{marginTop:12}}><Button loading={saving} disabled={locked} icon={<Save size={15}/>} onClick={()=>save()}>保存草稿</Button><Button loading={saving} disabled={locked} type="primary" icon={<CheckCircle2 size={15}/>} onClick={submit}>提交并锁定</Button></Space></Card></Col>
    </Row>
    <Card className="evidence-drawer"><Tabs items={[{key:'codebook',label:'Codebook',children:<pre className="ai-json">{JSON.stringify(assignment.codebook,null,2)}</pre>},{key:'changes',label:`修改轨迹 (${assignment.change_logs.length})`,children:<Collapse items={assignment.change_logs.map(item=>({key:String(item.id),label:`${item.field_path} · ${item.change_type} · ${new Date(item.changed_at).toLocaleString()}`,children:<pre className="ai-json">{JSON.stringify({before:item.old_value,after:item.new_value,versions:item.versions},null,2)}</pre>}))}/>},{key:'versions',label:'版本',children:<Descriptions column={3} items={Object.entries(assignment.versions).map(([key,value])=>({key,label:key,children:value}))}/>} ]}/></Card>
  </main>
}
