import { Button, Select, Table, Tag, Tooltip } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useNavigate } from 'react-router-dom'
import { api } from '../../api/client'
import { useWorkspace } from '../../stores/workspace'
import type { DataRecord, ProjectSchema, ViewConfig } from '../../types'
import { displayValue, fieldMap, getPath, setPath } from '../../utils/data'

const statusLabels:Record<string,string>={unreviewed:'未审校',in_progress:'审校中',approved:'已通过',rejected:'已拒绝',needs_review:'需复核'}
export function DataTable({schema,view,visiblePaths,onSelection}:{schema:ProjectSchema;view:ViewConfig;visiblePaths?:string[];onSelection:(ids:number[])=>void}){const navigate=useNavigate();const {records,replaceRecord}=useWorkspace();const map=fieldMap(schema.fields);const configured=visiblePaths??view.table?.columns??schema.fields.slice(0,6).map((f)=>f.key);const columns:ColumnsType<DataRecord>=configured.map((path)=>{
  if(path==='_review.status')return {title:'审校状态',key:path,width:120,render:(_,record)=><Tag color={record.review_status==='approved'?'green':record.review_status==='needs_review'?'orange':'default'}>{statusLabels[record.review_status]}</Tag>}
  const field=map[path];return {title:field?.label??path,key:path,dataIndex:path,sorter:(a,b)=>String(getPath(a.current_data,path)??'').localeCompare(String(getPath(b.current_data,path)??'')),ellipsis:true,render:(_,record)=>{const value=getPath(record.current_data,path);if(field?.type==='enum')return <Select size="small" value={value} options={field.options} style={{minWidth:140}} onClick={(e)=>e.stopPropagation()} onChange={async(next)=>{const updated=await api.updateRecord(record.id,setPath(record.current_data,path,next));replaceRecord(updated)}}/>;return <Tooltip title={displayValue(value)}><span className={record.changed_fields.includes(path)?'cell-changed':''}>{displayValue(value)}</span></Tooltip>}}
});columns.unshift({title:'校验',key:'validation',width:72,render:(_,record)=><Tag color={record.validation_status==='valid'?'green':'red'}>{record.validation_status==='valid'?'通过':'错误'}</Tag>});columns.push({title:'最后修改',dataIndex:'updated_at',width:168,render:(value)=>new Date(value).toLocaleString('zh-CN')},{title:'操作',key:'action',fixed:'right',width:90,render:(_,record)=><Button type="link" onClick={(e)=>{e.stopPropagation();navigate(`/project/${record.project_id??''}/record/${record.id}`)}}>详情</Button>});return <Table<DataRecord> rowKey="id" dataSource={records} columns={columns} rowClassName={(record)=>record.validation_status==='invalid'?'row-invalid':''} rowSelection={{onChange:(keys)=>onSelection(keys as number[])}} onRow={(record)=>({onDoubleClick:()=>navigate(`/project/${record.project_id??''}/record/${record.id}`)})} scroll={{x:Math.max(900,columns.length*160)}} pagination={{pageSize:20,showSizeChanger:true,showTotal:(total)=>`共 ${total} 条`}}/>}
